[book]
authors = ["Nolan CAROUGE"]
language = "en"
multilingual = false
src = "src"
title = "Exploring Cryptography with Rust"

[output.html]
mathjax-support = false

[preprocessor.katex]
after = ["links"]