name: CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo test --all --workspace

      - name: Download mdBook v0.4.34
        run: |
          MDVER=0.4.34
          curl -fsSL \
            https://github.com/rust-lang/mdBook/releases/download/v${MDVER}/mdbook-v${MDVER}-x86_64-unknown-linux-gnu.tar.gz \
            | tar xz -C /usr/local/bin mdbook

      - name: Cache mdbook-katex
        id: cache-katex
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/mdbook-katex
          key: ${{ runner.os }}-mdbook-katex-${{ hashFiles('**/Cargo.toml') }}

      - name: Install mdbook-katex
        if: steps.cache-katex.outputs.cache-hit != 'true'
        run: cargo install mdbook-katex

      - name: Build book
        run: |
          cd book
          mdbook build

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: book/book

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
